### ISSUE TITLE
can't get user info

### ISSUE THREAD

**Issue by sahilsk** [ajaxorg/node-github#44]
First, thanks for sharing this wonderful library. (:

I"m trying to get user information especially 'email' using following snippet.

``` js
		github.user.get( {
			user: 'xyz'
		}, function(err, user){
			console.log(user);
			cb(err,info)
		});
```

I am always getting information of authenticated user only. How to get information belonging to only user: 'xyz' ?

Any help would be great.

**Comment by burakkeles** [comment]
did you find any solution?

**Comment by sahilsk** [comment]
@burakkeles no i didn't get the solution and didn't had time back then to dig into it. I got skeptical about this project. So, i moved to a different project which has more features: [octonode](https://github.com/pksunkara/octonode#build-a-client-which-accesses-any-public-information)
